---
- name: Register Redhat_subscription
  hosts: all
  become: yes
  tasks:
  - name: Same as above but subscribe to a specific pool by ID.
    community.general.redhat_subscription:
      state: present
      username: tthamonwan
      password: 5tgb^YHN7ujm
      pool_ids: 2c94c44586179ec60186358a66a016fa
